title: Edison Zhao # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  A dedicated undergraduate computer science student at Oregon State University \
  with a keen interest in leveraging data to tackle intricate problems \
  aspires to pursue a career as a data scientist to address complex data-driven challenges.
  <br>
  Bachelor of Science in Computer Science at Oregon State University
  Bachelor of Science in Quantitative Economics at CUNY Queens College
  <br>
  <a href="https://www.linkedin.com/in/edison-z-91048960/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
