title: Edison Zhao # your name (or website title) here
logo: "/images/IMG_0712.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  A dedicated student, driven by a keen interest in leveraging data to address complex challenges, aspires to pursue a career as a data scientist.
  <br><br>
  B.Sc in Quantitative Economics at CUNY Queens College. Graduated with High Honors in Economics.
  <br><br>
  <a href="https://www.linkedin.com/in/edison-z-91048960/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
