title: Edison Zhao # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Quantitative Economics @CUNY Qeens College
  <br><br>
  Computer Science @Oregon State University
  <br><br>
  <a href="https://www.linkedin.com/in/edison-z-91048960/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
